/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/fleets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all fleets
         * @description Returns a paginated list of all indexed CAP-85 contract fleets.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of fleets to return (default 20, max 100) */
                    limit?: number;
                    /** @description Number of fleets to skip (default 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of fleets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Fleet"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleets/{owner}/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get fleet by owner address and tag */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description StrKey address of the executable owner contract */
                    owner: string;
                    /** @description Executable tag string (case-sensitive, exact) */
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fleet details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Fleet"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleets/{owner}/{tag}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List fleet members */
        get: {
            parameters: {
                query?: {
                    /** @description Filter to only currently active fleet members (default true) */
                    active_only?: boolean;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    owner: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fleet members list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FleetMember"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleets/{owner}/{tag}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verification history for a fleet */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    owner: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historical verification results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["VerificationResult"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleets/{owner}/{tag}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List release history for a fleet */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    owner: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of observed releases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FleetRelease"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fleets/{owner}/{tag}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trigger and fetch fleet verification
         * @description Verifies current on-chain executables of all active members against expected WASM hash.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Hex-encoded 32-byte expected WASM hash (defaults to fleet's current WASM hash) */
                    expected_wasm?: string;
                };
                header?: never;
                path: {
                    owner: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verification result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["VerificationResult"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect contract
         * @description Returns indexed fleet membership details and live resolved executable state.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    contract_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contract inspection result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ContractInspection"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginationMeta: {
            /** @example 100 */
            total: number;
            /** @example 20 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        FleetID: {
            /** @example CA3D5KRYMCMCZVACQY3CGINPVPUM2OAL6YHT3ZVM5C2MUMAA252AAAAB */
            Owner: string;
            /** @example vault-v1 */
            Tag: string;
        };
        Fleet: {
            id: components["schemas"]["FleetID"];
            /**
             * Format: byte
             * @description Base64-encoded WASM hash
             */
            current_wasm_hash?: string;
            /** @example 42 */
            member_count: number;
            /** @example 100000 */
            first_seen_ledger: number;
            /** @example 105432 */
            last_seen_ledger: number;
            /** @example 105432 */
            last_indexed_ledger: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FleetMember: {
            /** @example CB222222222222222222222222222222222222222222222222222222 */
            contract_id: string;
            fleet_id: components["schemas"]["FleetID"];
            /** Format: byte */
            wasm_hash: string;
            first_seen_ledger: number;
            last_seen_ledger: number;
            last_verified_ledger?: number | null;
            /** @example true */
            active: boolean;
        };
        FleetRelease: {
            /** @example 1 */
            id: number;
            fleet_id: components["schemas"]["FleetID"];
            /** Format: byte */
            old_wasm_hash?: string | null;
            /** Format: byte */
            new_wasm_hash: string;
            /** @example 102000 */
            ledger: number;
            /** @example 3b940e53a2ef9f8... */
            tx_hash: string;
            /** Format: date-time */
            observed_at: string;
        };
        /**
         * @example HEALTHY
         * @enum {string}
         */
        VerificationStatus: "HEALTHY" | "DRIFT" | "BROKEN_REFERENCE" | "INCOMPLETE" | "UNKNOWN";
        VerificationResult: {
            /** @example 10 */
            id?: number;
            fleet_id: components["schemas"]["FleetID"];
            /** Format: byte */
            expected_wasm_hash: string;
            /** @example 15 */
            total_members: number;
            /** @example 15 */
            matching_members: number;
            /** @example 0 */
            mismatching_members: number;
            /** @example 0 */
            missing_members: number;
            /** @example 105432 */
            indexed_through: number;
            status: components["schemas"]["VerificationStatus"];
            /** Format: date-time */
            verified_at: string;
        };
        ContractInspection: {
            /** @example CA3D5KRYMCMCZVACQY3CGINPVPUM2OAL6YHT3ZVM5C2MUMAA252AAAAB */
            contract_id: string;
            /** @example true */
            is_member: boolean;
            member?: components["schemas"]["FleetMember"];
            resolved: {
                /** @example EXTERNAL_REF */
                kind?: string;
                fleet?: components["schemas"]["FleetID"];
                /** Format: byte */
                wasm_hash?: string;
            };
        };
    };
    responses: {
        /** @description Structured error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @example FLEET_NOT_FOUND */
                        code: string;
                        /** @example Fleet was not found */
                        message: string;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
